jobs:
  close-issues:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        close-issue-message: This issue was closed because it has been inactive for
          14 days.
        close-pr-message: This pull request was closed because it has been inactive
          for 14 days. Please reopen if you still intend to submit this pull request.
        days-before-issue-close: 0
        days-before-issue-stale: 14
        days-before-pr-close: 14
        days-before-pr-stale: -1
        exempt-issue-labels: bug,enhancement,keep
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: no-activity
        stale-pr-label: no-activity
name: Close inactive issues
on:
  repository_dispatch:
    types: trigger-ga___close-issue.yml
